package xyz.oleolegka.gachimuchi.data

import android.content.Context
import androidx.room.ColumnInfo
import androidx.room.Dao
import androidx.room.Database
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.Insert
import androidx.room.PrimaryKey
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.test.core.app.ApplicationProvider
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import xyz.oleolegka.gachimuchi.data.db.AliasDao
import xyz.oleolegka.gachimuchi.data.db.AliasEntity
import xyz.oleolegka.gachimuchi.data.db.AppDatabase
import xyz.oleolegka.gachimuchi.data.db.EventDao
import xyz.oleolegka.gachimuchi.data.db.EventEntity
import xyz.oleolegka.gachimuchi.data.db.ExerciseDao
import xyz.oleolegka.gachimuchi.data.db.ExerciseEntity
import xyz.oleolegka.gachimuchi.data.db.LOCAL_SPACE_ID
import xyz.oleolegka.gachimuchi.data.db.SlotDao
import xyz.oleolegka.gachimuchi.data.db.SlotEntity
import xyz.oleolegka.gachimuchi.domain.ExerciseForm
import xyz.oleolegka.gachimuchi.domain.ProgramBlock
import xyz.oleolegka.gachimuchi.domain.ProgramGroup
import xyz.oleolegka.gachimuchi.domain.WorkoutProgram
import xyz.oleolegka.gachimuchi.domain.strengthSetOf
import xyz.oleolegka.gachimuchi.domain.toPayload

/**
 * Version 1 of the schema, exactly as it shipped: the four tables that existed before the
 * timer, and nothing else.
 *
 * Declared as a real Room database so that ROOM generates the old DDL. Writing those
 * CREATE TABLE statements by hand would mean the migration is tested against a schema
 * invented here, which is precisely the schema that cannot be wrong.
 */
@Database(
    entities = [EventEntity::class, ExerciseEntity::class, AliasEntity::class, SlotEntity::class],
    version = 1,
    exportSchema = false,
)
abstract class SchemaV1Database : RoomDatabase() {
    abstract fun events(): EventDao
    abstract fun exercises(): ExerciseDao
    abstract fun aliases(): AliasDao
    abstract fun slots(): SlotDao
}

/*
 * Version 2 of the program tables, exactly as they shipped: no link to an exercise and no
 * category. Same reasoning as [SchemaV1Database] — the old DDL is generated by Room from
 * these classes rather than written out here, so the migration is tested against the schema
 * that actually existed on a phone and not against one invented in a test.
 */

@Entity(tableName = "programs", indices = [Index(value = ["space_id", "id"])])
data class ProgramEntityV2(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(name = "space_id") val spaceId: Long = LOCAL_SPACE_ID,
    val name: String,
    @ColumnInfo(name = "prepare_sec") val prepareSec: Int,
    val position: Int = 0,
    @ColumnInfo(name = "created_at") val createdAt: String,
)

@Entity(
    tableName = "program_groups",
    indices = [Index(value = ["program_id"])],
    foreignKeys = [
        ForeignKey(
            entity = ProgramEntityV2::class,
            parentColumns = ["id"],
            childColumns = ["program_id"],
            onDelete = ForeignKey.CASCADE,
        )
    ],
)
data class ProgramGroupEntityV2(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(name = "program_id") val programId: Long,
    val name: String,
    val position: Int,
    val repeats: Int,
    @ColumnInfo(name = "rest_between_repeats_sec") val restBetweenRepeatsSec: Int,
    @ColumnInfo(name = "rest_after_sec") val restAfterSec: Int,
)

@Entity(
    tableName = "program_blocks",
    indices = [Index(value = ["group_id"])],
    foreignKeys = [
        ForeignKey(
            entity = ProgramGroupEntityV2::class,
            parentColumns = ["id"],
            childColumns = ["group_id"],
            onDelete = ForeignKey.CASCADE,
        )
    ],
)
data class ProgramBlockEntityV2(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(name = "group_id") val groupId: Long,
    val name: String,
    val position: Int,
    @ColumnInfo(name = "work_sec") val workSec: Int,
    @ColumnInfo(name = "rest_sec") val restSec: Int,
    val repeats: Int,
)

@Dao
interface ProgramDaoV2 {
    @Insert
    suspend fun insertProgram(program: ProgramEntityV2): Long

    @Insert
    suspend fun insertGroup(group: ProgramGroupEntityV2): Long

    @Insert
    suspend fun insertBlock(block: ProgramBlockEntityV2): Long
}

@Database(
    entities = [
        EventEntity::class,
        ExerciseEntity::class,
        AliasEntity::class,
        SlotEntity::class,
        ProgramEntityV2::class,
        ProgramGroupEntityV2::class,
        ProgramBlockEntityV2::class,
    ],
    version = 2,
    exportSchema = false,
)
abstract class SchemaV2Database : RoomDatabase() {
    abstract fun events(): EventDao
    abstract fun exercises(): ExerciseDao
    abstract fun programs(): ProgramDaoV2
}

/**
 * Migrating a phone that already has a training journal on it.
 *
 * The thing being protected is not the new tables — a mistake there fails loudly on the
 * next open. It is the JOURNAL: `fallbackToDestructiveMigration` is deliberately not
 * enabled (see AppDatabase), so a broken migration must be caught here rather than on a
 * phone where the only copy of somebody's training history lives.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class MigrationTest {

    private val context: Context = ApplicationProvider.getApplicationContext()
    private val dbName = "migration-test.db"
    private var opened: RoomDatabase? = null

    @After
    fun tearDown() {
        opened?.close()
        context.deleteDatabase(dbName)
    }

    /** Creates a version 1 database with some history in it, and closes it. */
    private suspend fun writeVersion1() {
        val v1 = Room.databaseBuilder(context, SchemaV1Database::class.java, dbName).build()
        opened = v1

        val exerciseId = v1.exercises().insert(
            ExerciseEntity(
                name = "Hangs 20 mm", form = ExerciseForm.HOLD.code,
                createdAt = "2026-08-01T10:00:00", edgeMm = 20.0,
                protocolWorkSec = 7.0, protocolRestSec = 3.0,
            )
        )
        val set = strengthSetOf(
            exercise = xyz.oleolegka.gachimuchi.domain.ExerciseRef(
                id = exerciseId, name = "Bench press", form = ExerciseForm.STRENGTH,
            ),
            opDate = "2026-08-01", reps = 5, weightKg = 80.0,
        )
        v1.events().insert(
            EventEntity(ts = "2026-08-01T10:00:00", type = set.type, payload = set.toPayload())
        )
        v1.aliases().upsert(AliasEntity(key = "bench", value = exerciseId))
        v1.slots().insert(
            SlotEntity(
                name = "Gym", atTime = "19:00", repeatRule = "weekly",
                anchorDate = "2026-08-01", createdAt = "2026-08-01T09:00:00",
            )
        )
        v1.close()
        opened = null
    }

    /**
     * Creates a version 2 database with a program already in it, and closes it. This is the
     * phone the 2 -> 3 migration actually runs on: one that has been using the timer.
     */
    private suspend fun writeVersion2(): Long {
        val v2 = Room.databaseBuilder(context, SchemaV2Database::class.java, dbName).build()
        opened = v2

        v2.exercises().insert(
            ExerciseEntity(
                name = "Hangs 20 mm", form = ExerciseForm.HOLD.code,
                createdAt = "2026-08-01T10:00:00", edgeMm = 20.0,
                protocolWorkSec = 7.0, protocolRestSec = 3.0,
            )
        )
        val programId = v2.programs().insertProgram(
            ProgramEntityV2(
                name = "Hangboard repeaters 7:3", prepareSec = 15, position = 0,
                createdAt = "2026-08-01T10:00:00",
            )
        )
        val groupId = v2.programs().insertGroup(
            ProgramGroupEntityV2(
                programId = programId, name = "Repeaters", position = 0, repeats = 4,
                restBetweenRepeatsSec = 180, restAfterSec = 0,
            )
        )
        v2.programs().insertBlock(
            ProgramBlockEntityV2(
                groupId = groupId, name = "Hang", position = 0,
                workSec = 7, restSec = 3, repeats = 6,
            )
        )
        v2.close()
        opened = null
        return programId
    }

    private fun openVersion2(): AppDatabase =
        Room.databaseBuilder(context, AppDatabase::class.java, dbName)
            .addMigrations(*AppDatabase.MIGRATIONS)
            .build()
            .also { opened = it }

    @Test
    fun `the journal, the catalog, the aliases and the slots all survive the upgrade`() = runTest {
        writeVersion1()

        val v2 = openVersion2()

        val events = v2.events().all()
        assertEquals(1, events.size)
        assertTrue(events.single().payload.contains("Bench press"))

        val exercises = v2.exercises().all()
        assertEquals(1, exercises.size)
        assertEquals("Hangs 20 mm", exercises.single().name)
        assertEquals(20.0, exercises.single().edgeMm!!, 1e-9)

        assertNotNull(v2.aliases().byKey("bench"))
        assertEquals(1, v2.slots().all().size)
    }

    @Test
    fun `the program tables exist after the upgrade and accept a program`() = runTest {
        writeVersion1()

        val v2 = openVersion2()
        val repo = ProgramRepository(v2)

        assertEquals(0, repo.count())
        val id = repo.save(
            WorkoutProgram(
                name = "Repeaters",
                prepareSec = 15,
                groups = listOf(
                    ProgramGroup(
                        name = "Repeaters",
                        blocks = listOf(ProgramBlock("Hang", workSec = 7, restSec = 3, repeats = 6)),
                        repeats = 4,
                        restBetweenRepeatsSec = 180,
                    )
                ),
            )
        )

        val stored = repo.programById(id)
        assertNotNull(stored)
        assertEquals("Repeaters", stored!!.name)
        assertEquals(6, stored.groups.single().blocks.single().repeats)
    }

    @Test
    fun `opening the upgraded database a second time passes Room's own schema check`() = runTest {
        writeVersion1()

        // the first open runs the migration and writes the new identity
        openVersion2().also { it.events().count() }.close()
        opened = null

        // the second open takes the "already at the right version" path, where Room
        // compares the database against the entity definitions and refuses a mismatch
        val again = openVersion2()
        assertEquals(1, again.events().count())
        assertEquals(0, again.programs().countPrograms())
    }

    @Test
    fun `a fresh install creates the current version directly, without any migration`() = runTest {
        val fresh = openVersion2()
        assertEquals(0, fresh.events().count())
        assertEquals(0, fresh.programs().countPrograms())
    }

    // --- version 2 -> 3: the program's exercise link and its category -----------------------

    @Test
    fun `a program written before the upgrade survives it, unlinked and uncategorised`() = runTest {
        val programId = writeVersion2()

        val v3 = openVersion2()
        val stored = ProgramRepository(v3).programById(programId)

        assertNotNull("a hand-written protocol must not be lost to a schema change", stored)
        assertEquals("Hangboard repeaters 7:3", stored!!.name)
        assertEquals(15, stored.prepareSec)
        assertEquals(6, stored.groups.single().blocks.single().repeats)
        assertEquals(4, stored.groups.single().repeats)
        // the new columns read as "nothing was said", which is what was true before
        assertNull(stored.exerciseId)
        assertEquals("", stored.category)
    }

    @Test
    fun `after the upgrade a program can be linked and filed, and both come back`() = runTest {
        val programId = writeVersion2()
        val v3 = openVersion2()
        val repo = ProgramRepository(v3)
        val exerciseId = v3.exercises().all().single().id

        repo.save(repo.programById(programId)!!.copy(category = "Hangboard"))
        repo.linkExercise(programId, exerciseId)

        val stored = repo.programById(programId)!!
        assertEquals(exerciseId, stored.exerciseId)
        assertEquals("Hangboard", stored.category)
        // and linking did not disturb the protocol itself
        assertEquals(6, stored.groups.single().blocks.single().repeats)
    }

    @Test
    fun `the upgraded database passes Room's schema check on the next open`() = runTest {
        writeVersion2()

        openVersion2().also { it.programs().countPrograms() }.close()
        opened = null

        // the second open compares the database against the entity definitions and refuses a
        // mismatch, which is what would catch a column type or a default written wrongly
        val again = openVersion2()
        assertEquals(1, again.programs().countPrograms())
    }
}
